spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StarzoneCN/spring-cloud-config-repository/
          force-pull: true
server:
  port: 1201

encrypt:
  key: didispace

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

